### ISSUE TITLE
当たり判定の変更

### ISSUE THREAD

**Issue by uchiyu** [vitamiena/GyozaBrothers#22]
プレイヤーに当たるものの直前の座標を算出して、踏む判定などを行えるように変更する。
直前の座標の算出はAbstractCharacterでのみに使用可能
動かないAbstractMaterialなどは衝突判定のみで判断する。

**Comment by vitamiena** [comment]
その方針だと、今後Structureも動くからどうなるか微妙な気がする

**Comment by uchiyu** [comment]
Structureどう動かすか決めてないから、どうなるんか分からんかったけど、
動くなら、AbstractCharacterみたいになるだろうと考えてとりあえずこうした
